language: go
go_import_path: github.com/simplechain-org/go-simplechain
jobs:
  allow_failures:
    - stage: build
      os: osx
      go: 1.13.x

  include:
    # This builder only tests code linters on go 1.13.x
    - stage: lint
      os: linux
      dist: xenial
      go: 1.13.x
      env:
        - lint
      git:
        submodules: false # avoid cloning simplechain/tests
      script:
        - go run build/ci.go lint

    # go latest, linux
    - stage: build
      os: linux
      dist: xenial
      go: 1.14.x
      env:
        - GO111MODULE=on
      script:
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES

    # go 1.13.x, linux, merge
    - stage: build
      if: type = pull_request
      os: linux
      arch: amd64
      dist: xenial
      go: 1.13.x
      env:
        - GO111MODULE=on
      script:
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES

    # go 1.13.x, mac, merge
    - stage: build
      if: type = pull_request
      os: osx
      osx_image: xcode11.3
      go: 1.13.x
      env:
        - GO111MODULE=on
      script:
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES

deploy:
  - provider: script
    script: docker run -e GITHUB_TOKEN=$GITHUB_TOKEN --rm --privileged -v $TRAVIS_BUILD_DIR:/go/src/github.com/simplechain-org/go-simplechain -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/simplechain-org/go-simplechain mailchain/goreleaser-xcgo --rm-dist
    skip_cleanup: true
    on:
      tags: true
      repo: simplechain-org/go-simplechain
      branch: master
      condition: $DEPLOY = true
